all:
  .settings:
    twig_extensions: []
    # See Twig_Environment options for available options
    twig_options:
        debug:              %SF_DEBUG%
        cache:              %SF_APP_CACHE_DIR%
        auto_reload:        %SF_DEBUG%
